Repository Kuwarsaab/Learn-Spring-Framework, pull requests merged in 2024-10, with the labels that each got.

#1 Added PacmanGame
  src/main/java/com/Spring/Learn_Spring_Framework/AppGamingBasic.java
  src/main/java/com/Spring/Learn_Spring_Framework/game/PacmanGame.java
Labels: hactoberfest, hactoberfest-accepted

#2 Done proper redirection of the markdown document
  README.md
Labels: hactoberfest, hactoberfest-accepted

#3 Added Spring Bean
  src/main/java/com/Spring/Learn_Spring_Framework/App01GamingBasic.java
  src/main/java/com/Spring/Learn_Spring_Framework/App02HelloWorldSpring.java
  src/main/java/com/Spring/Learn_Spring_Framework/AppGamingBasic.java
  src/main/java/com/Spring/Learn_Spring_Framework/HelloWorldConfiguration.java
  src/main/java/com/Spring/Learn_Spring_Framework/LearnSpringFrameworkApplication.java
Labels: hactoberfest, hactoberfest-accepted

#4 Create gitCheatSheet.md
  gitCheatSheet.md
Labels: hacktoberfest, hacktoberfest-accepted

#5 Enhanced the project by using spring annotations and other features
  src/main/java/com/Spring/Learn_Spring_Framework/App01GamingBasic.java
  src/main/java/com/Spring/Learn_Spring_Framework/GamingAppLauncherApplication.java
  src/main/java/com/Spring/Learn_Spring_Framework/game/GameRunner.java
  src/main/java/com/Spring/Learn_Spring_Framework/game/MarioGame.java
  src/main/java/com/Spring/Learn_Spring_Framework/game/PacmanGame.java
  src/main/java/com/Spring/Learn_Spring_Framework/game/SuperContraGame.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#7 Add Model Controller Service Project using Spring Boot
  pom.xml
  src/main/java/com/Spring/Learn_Spring_Framework/friendCollectionSystem/FriendsListApplication.java
  src/main/java/com/Spring/Learn_Spring_Framework/friendCollectionSystem/constants/FriendsListConstants.java
  src/main/java/com/Spring/Learn_Spring_Framework/friendCollectionSystem/constants/FriendsListErrorCodes.java
  src/main/java/com/Spring/Learn_Spring_Framework/friendCollectionSystem/controller/FriendCollectionController.java
  src/main/java/com/Spring/Learn_Spring_Framework/friendCollectionSystem/dto/model/Friends.java
  src/main/java/com/Spring/Learn_Spring_Framework/friendCollectionSystem/dto/request/CreateOrUpdateFriendRequest.java
  src/main/java/com/Spring/Learn_Spring_Framework/friendCollectionSystem/exceptions/CustomizedResponseEntityExceptionHandler.java
  src/main/java/com/Spring/Learn_Spring_Framework/friendCollectionSystem/exceptions/ErrorCode.java
  src/main/java/com/Spring/Learn_Spring_Framework/friendCollectionSystem/exceptions/ExceptionResponse.java
  src/main/java/com/Spring/Learn_Spring_Framework/friendCollectionSystem/exceptions/FriendListException.java
  src/main/java/com/Spring/Learn_Spring_Framework/friendCollectionSystem/repository/FriendsListRepository.java
  src/main/java/com/Spring/Learn_Spring_Framework/friendCollectionSystem/service/FriendsListService.java
  src/main/java/com/Spring/Learn_Spring_Framework/friendCollectionSystem/service/FriendsListServiceImpl.java
  src/main/resources/application.properties
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024
